main/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name= "main"
urlpatterns = [
    path('', views.Visits.as_view(), name="visits"),
    path('login', views.Login.as_view(), name='login'),  
    path('logout', views.Logout.as_view(), name='logout'),  
    path('remind_password', views.SendPassword.as_view(), name="remind_password"),
    path('add_security', views.AddSecurity.as_view(), name="add_security"),
    path('delete_security', views.DeleteSecurity.as_view(), name="delete_security"),
    path('delete_student', views.DeleteStudent.as_view(), name="delete_student"),
    path('stream', views.live_stream, name="stream"),
    path('student_stream', views.add_student_stream, name="student_stream"),
    path('show_stream', views.StreamView.as_view(), name="show_stream"),
    path('add_student', views.AddStudentStreamView.as_view(), name="add_student"),
    path('start_stop_stream', views.StartStopStream.as_view(), name="start_stop_stream"),
    path('start_student_stream', views.StartStudentStream.as_view(), name="start_student_stream"),
    path('download/(?P<path>.*)$', views.Download.as_view(), name="download"),

]

shagface/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Face(models.Model):
    img_url = models.TextField(blank=True)
    absolute_path = models.TextField(blank=True)

class Student(models.Model):
    email = models.TextField(default="") 
    fullname= models.TextField(default="") 
    images_urls = models.ManyToManyField(Face, related_name='faces',  blank=True)
    group = models.TextField(default="")
    course = models.TextField(default="")
    def __str__(self):
        return self.fullname

class Security(models.Model):
    email = models.TextField(default="") 
    password = models.TextField(default="") 
    login = models.TextField(default="") 
    fullname= models.TextField(default="") 
    def __str__(self):
        return self.fullname

class Visit(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    visit_time = models.DateTimeField(default=timezone.localtime(timezone.now()))
    def __str__(self):
        return self.student.fullname

class BotUser(models.Model):
    chat_id = models.IntegerField(null=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.chat_id)

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .models import Security, Student, Visit, Face
import os

from django.db.models import Q

from django.contrib.auth.models import User as MainAdmin

from django.http import HttpResponse, Http404

from .modules.hashutils import check_pw_hash, make_pw_hash
from .modules.sendEmail import *

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .modules.utils import *
from .modules.TimedValue import TimedValue

from django.contrib.auth.hashers import check_password

from .Classes.Camera import Camera
from .Classes.Bot import Bot
from django.http import StreamingHttpResponse
import cv2
import numpy as np

from django.views.decorators.gzip import gzip_page

from django.template import loader, Context

from .face_recognition.utils import *

from django.http import JsonResponse

COUNT_BLOG_ON_PAGE = 50
STUDENT_PHOTOS = 4
TIME_TO_WAIT = 3 # Время которое пройдет после того как камера распознает студента чтобы показать следующую картинку

cam = None
class CameraAction():
    IS_STOP = True
    cam = cam
    timed_value = TimedValue(TIME_TO_WAIT)
    current_student = None

class Logout(View):
    def post(self, request):
        try:
            del request.session["user_id"]
        except:
            print("error")
        return redirect(reverse('main:login'))

class Download(View):
    def post(self, request, path):
        file_path = os.path.join(settings.MEDIA_ROOT, path)
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                return response
        raise Http404

class SendPassword(View):
    def get(self, request):
        return render(request, 'remind_password.html', {})

    def post(self, request):
        email = post_parameter(request, "email")
        if email:
            admin = MainAdmin.objects.filter(email=email).first()
            if admin:
                send_email(admin.password, "Ваш пароль", admin.email)
            else:
                return render(request, 'remind_password.html', {
                    "login_error" : "Пользователяс таким Email не найдено!",
                })
        return redirect(reverse("main:login"))


class Login(View):
    def get(self, request):
        return render(request, 'login.html', {})

    def post(self, request):
        email_or_username = post_parameter(request, "username")
        password = post_parameter(request, "pass")
        user = None
        role = "admin"

        login_valid = (settings.ADMIN_LOGIN == email_or_username or settings.ADMIN_EMAIL == email_or_username)
        pwd_valid = check_password(password, settings.ADMIN_PASSWORD)

        if login_valid and pwd_valid:
            user = MainAdmin.objects.filter(Q(username=email_or_username) | Q(email=email_or_username)).first()
            role = "main_admin"
            request.session["user_id"] = user.id
            request.session["role"] = role
            return redirect(reverse('main:visits'))
            
        
        user = Security.objects.filter(email=email_or_username).first()
        if not user:
            user = Security.objects.filter(login=email_or_username).first()  

        if user:
            if check_pw_hash(password, user.password):
                request.session["user_id"] = user.id
                request.session["role"] = role
                return redirect(reverse('main:visits'))
            else:
                return render(request, 'login.html', {
                    "login_error" : "Неверный логин или пароль!",
                })
        else:
            return render(request, 'login.html', {
                "login_error" : "Неверный логин или пароль!",
            })
            
class AddSecurity(View):
    def get(self, request):
        if not get_current_user(request):
            return redirect(reverse('main:login'))
        return render(request, 'add_security.html', {
            "user": get_current_user(request),  
            "nomargin": True,
        })
    
    def post(self, request):
        email = post_parameter(request, "email")
        login = post_parameter(request, "login")
        password = post_parameter(request, "pass")
        fullname = post_parameter(request, "fullname")

        hash_password = make_pw_hash(password)

        if len(Security.objects.filter(Q(email=email) | Q(login=login))) > 0:
            return render(request, 'add_security.html', {
                "add_error" : "Такой пользователь уже сущетсвует!",
            })
        Security.objects.create(email=email, login=login, password=hash_password, fullname=fullname)
        return render(request, 'add_security.html', {
            "success" : "Вы успешно добавили охранника!",
        })


class DeleteSecurity(View):
    def get(self, request):
        if not get_current_user(request):
            return redirect(reverse('main:login'))
        securities = Security.objects.all()
        return render(request, 'delete_security.html', {
            "user": get_current_user(request),  
            "securities": securities
        })
    
    def post(self, request):
        security_id = post_parameter(request, "id")
        security =Security.objects.filter(id=security_id).first()
        if not security:
            return render(request, 'delete_security.html', {
                "delete_error" : "Не удалось найти пользователя для удаления!",
            })
        security.delete()
        return render(request, 'delete_security.html', {
            "success" : "Вы успешно удалили охранника!",
            "securities": Security.objects.all()
        })

class DeleteStudent(View):
    def get(self, request):
        if not get_current_user(request):
            return redirect(reverse('main:login'))

        students = Student.objects.all()
        return render(request, 'delete_student.html', {
            "user": get_current_user(request),  
            "students": students
        })
    
    def post(self, request):
        student_id = post_parameter(request, "id")
        student = Student.objects.filter(id=student_id).first()
        if not student:
            return render(request, 'delete_student.html', {
                "delete_error" : "Не удалось найти пользователя для удаления!",
            })
        delete_images(student)
        student.delete()
        if len(Student.objects.all()) == 0:
            clear_face_uml()
        else:
            train()
        return render(request, 'delete_student.html', {
            "success" : "Вы успешно удалили студента!",
            "students": Student.objects.all()
        })

class Visits(View):
    if not BotAction.bot:
        print("BOT STARTED")
        BotAction.bot = Bot()
        
    def get(self, request):
        if not get_current_user(request):
            return redirect(reverse('main:login'))

        return render(request, 'visits.html', {
            "user": get_current_user(request),  
            "nomargin": True,
            "visits": Visit.objects.all()
        })

def gen_student():
    count = 1
    while True:
        if not CameraAction.IS_STOP and CameraAction.timed_value.has_time_passed() and count <= STUDENT_PHOTOS:
            frame = CameraAction.cam.get_frame_as_image()
            is_added, image = add_student(frame, CameraAction.current_student, count)
            if is_added:
                CameraAction.timed_value = TimedValue(TIME_TO_WAIT)
                count += 1
            if count > STUDENT_PHOTOS:
                train()
            yield(b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + image + b'\r\n\r\n')
        elif not CameraAction.cam:
            blank_image = create_blank(500, 500, (250,250,250)) 
            yield(b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + blank_image +  b'\r\n\r\n')
        elif count > STUDENT_PHOTOS:
            CameraAction.cam.stop()    
            CameraAction.cam = None
            CameraAction.IS_STOP = True
            break
        else:
            frame = CameraAction.cam.get_frame_as_image()
            img = recognise_face_without_title(frame)
            yield(b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + img +  b'\r\n\r\n')

@gzip_page
def add_student_stream(request):
    try:
        return StreamingHttpResponse(gen_student(), content_type="multipart/x-mixed-replace;boundary=frame")
    except: 
        pass

class AddStudentStreamView(View):
    def get(self, request):
        CameraAction.IS_STOP = True
        return render(request, 'add_student.html', {
            "user" : get_current_user(request),
            "nomargin": True,
            "TIME_TO_WAIT": TIME_TO_WAIT,
        })


def gen():
    while True:
        if not CameraAction.IS_STOP:
            try:
                frame = CameraAction.cam.get_frame_as_image()
                image = recognise_face(frame)
                yield(b'--frame\r\n'
                    b'Content-Type: image/jpeg\r\n\r\n' + image + b'\r\n\r\n')
            except:
                yield(b'--frame\r\n'
                    b'Content-Type: image/jpeg\r\n\r\n' + create_blank(500, 500, (250,250,250)) + b'\r\n\r\n')

@gzip_page
def live_stream(request):
    try:
        return StreamingHttpResponse(gen(), content_type="multipart/x-mixed-replace;boundary=frame")
    except: 
        pass

class StreamView(View):
    def get(self, request):
        return render(request, 'stream.html', {
            "user" : get_current_user(request),
            "nomargin": True,
        })

class StartStopStream(View):
    def post(self, request):
        is_stop = post_parameter(request, "is_stop")
        if is_stop == "true":

main/templates/acc_active_email.html
{% autoescape off %}
Привет {{ user.username }},
Пожалуйста подтверди свою почту на сайте {{domain}}, перейдя по ссылке
http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

main/templates/add_security.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <title>ShagFace</title>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/search.css'%}">
    <link rel="stylesheet" href="{%static 'css/pagination.css'%}">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
{% endblock %}

{% block header_button12 %}active{% endblock %}
{% block header_button6 %}active{% endblock %}


{% block content %}
   
   <div class="container-login100 p-0">
        <div class="wrap-login100 ">
            <form class="login100-form validate-form flex-sb flex-w" method="post" action="{% url 'main:add_security'%}">{% csrf_token %}
                <span class="login100-form-title p-b-51">
                    Добавить охранника
                </span>

                {% if add_error%}
                    <div class="error">
                        {{add_error}}
                    </div>
                {% elif success%}
                    <div class="success">
                        {{success}}
                    </div>
                {%endif%}
                
                <div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели данные">
                    <input class="input100" type="text" name="login" placeholder="Логин">
                    <span class="focus-input100"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели данные">
                    <input class="input100" type="text" name="email" placeholder="Email">
                    <span class="focus-input100"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели данные">
                    <input class="input100" type="text" name="fullname" placeholder="ФИО">
                    <span class="focus-input100"></span>
                </div>
                
                <div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели Пароль">
                    <input class="input100" type="password" name="pass" placeholder="Пароль">
                    <span class="focus-input100"></span>
                </div>

                <div class="container-login100-form-btn m-t-17">
                    <button class="login100-form-btn">
                        Добавить
                    </button>
                </div>

            </form>
        </div>
    </div>
    
{% endblock %}

main/templates/add_student.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <title>ShagFace</title>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/search.css'%}">
    <link rel="stylesheet" href="{%static 'css/pagination.css'%}">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
{% endblock %}

{% block header_butto12 %}active{% endblock %}
{% block header_button5 %}active{% endblock %}


{% block content %}

    <span class="title-text">Добавить студента</span>

    <div class="col-xl-6 col-sm-12">
        <div class="form-group">
            <div class="wrap-input100 validate-input m-b-16 col-xl-12 col-sm-12 p-0">                                            
                <div class="card shadow-sm x-shadow-fade-in">
                    <input type="text" class="input100" required name="fullname" id="fullname" placeholder=" Ф.И.О" title=" Ф.И.О">
                    <span class="focus-input100"></span>  
                </div>                                            
            </div>
        </div>
        <div class="form-group">
            <div class="wrap-input100 validate-input m-b-16 col-xl-12 col-sm-12 p-0">                        
                <div class="card shadow-sm x-shadow-fade-in">
                    <input type="email" name="email" class="input100" required name="email" id="email" placeholder="Email" title="Ваш Email">
                    <span class="focus-input100"></span> 
                </div>                                            
            </div>
        </div>
        <div class="form-group">
            <div class="wrap-input100 validate-input m-b-16 col-xl-12 col-sm-12 p-0">                                           
                <div class="card shadow-sm x-shadow-fade-in">
                    <input type="text" name="group" class="input100" required id="group"  placeholder="Группа" title="Группа">
                    <span class="focus-input100"></span>
                </div>                                            
            </div>
        </div>
        <div class="form-group">
            <div class="wrap-input100 validate-input m-b-16 col-xl-12 col-sm-12 p-0">                                           
                <div class="card shadow-sm x-shadow-fade-in">
                    <input type="text" name="course" class="input100" required id="course"  placeholder="Курс" title="Курс">
                    <span class="focus-input100"></span>
                </div>                                            
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-sm-12">
                                            
        <div class="camera-panel-student" id="camera-panel">
            <form action='{% url "main:start_student_stream"%}' method="POST">{% csrf_token %}
                <img class="start-video-student" id="start" src="{% static "images/icons/camera-icons/play.png"%}" title="Start Stream"/>
            </form>
        </div>
        

        <div class="form-group">
            <img style="-webkit-user-select: none;" class="cam-stream-student" id="stream" src="{% static "images/white.png"%}">            
        </div>

        <div class="form-group">
            <img style="-webkit-user-select: none;" class="cam-stream-student" id="face_position" src="{% static "preview_faces/face1.jpg"%}">            
        </div>

        <div class="form-group">
            <span>Смотрите в камеру под разными углами</span>
        </div>
    </div>    

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{%static "js/stream.js"%}"></script>
    <script type="text/javascript">
        function sleep(sec) {
           return new Promise(resolve => setTimeout(resolve, sec*1000));
        }

        const img = document.getElementById("stream");
        

        $("#start").on("click", function(){
            var fullname = $("#fullname")[0].value
            var email = $("#email")[0].value
            var group = $("#group")[0].value
            var course = $("#course")[0].value

            if(fullname.length == 0 || email.length == 0 || group.length == 0 || course.length == 0){
                alert("Заполните данные о студенте прежде чем снимать его лицо!")
                return;
            }

            $.ajax({
                url: '{% url "main:start_student_stream"%}',
                data: {
                'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
                'fullname': fullname,
                'email': email,
                'group': group,
                'course': course,
                },
                type: "POST",
                dataType: 'json',
                success: async function (data) {
                    if(data["error"]){
                        alert(data["error"])
                    }else{
                        img.src = '{% url "main:student_stream"%}';
                        await sleep(1)
                        for(var i = 1; i <= 4; i++){
                            $("#face_position")[0].src = "http://127.0.0.1:8000/static/preview_faces/face" + i + ".jpg"
                            await sleep({{TIME_TO_WAIT}})
                        }
                        await sleep(1);
                        $("#face_position")[0].src = "{% static "preview_faces/face1.jpg"%}";
                        img.src = "{% static "images/white.png"%}";
                    }
                }
            });
        })
    </script>
{%endblock%}

main/templates/delete_security.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <title>ShagFace</title>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/search.css'%}">
    <link rel="stylesheet" href="{%static 'css/pagination.css'%}">
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/b-1.6.2/r-2.2.5/sc-2.0.2/datatables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/b-1.6.2/r-2.2.5/sc-2.0.2/datatables.min.js"></script>

    <script src="{%static 'js/table.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    
{% endblock %}

{% block header_button8 %}active{% endblock %}
{% block header_button1 %}active{% endblock %}


{% block content %}

    <span class="title-text">Удалить охранника</span>

   <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th class="th-sm">Email
        </th>
        <th class="th-sm">ФИО
        </th>
        <th class="th-sm">Логин
        </th>
        <th class="th-sm">Удалить
        </th>
        </tr>
    </thead>
    <tbody>
        {% for item in securities %}
        <tr>
        <td>{{item.email}}</td>
        <td>{{item.fullname}}</td>
        <td>{{item.login}}</td>
        <td class="p-0">
            <form action="{% url 'main:delete_security'%}" method="POST" >{% csrf_token %}
                <input type="hidden" name="id" value="{{item.id}}"/>
                <button type="submit" class="delete-security-button">Удалить</button>
            </form>
        </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
        <th>Email
        </th>
        <th>ФИО
        </th>
        <th>Логин
        </th>
        <th>Удалить
        </th>
        </tr>
    </tfoot>
    </table>
   
    
{% endblock %}

main/templates/delete_student.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <title>ShagFace</title>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/search.css'%}">
    <link rel="stylesheet" href="{%static 'css/pagination.css'%}">
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/b-1.6.2/r-2.2.5/sc-2.0.2/datatables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/b-1.6.2/r-2.2.5/sc-2.0.2/datatables.min.js"></script>

    <script src="{%static 'js/table.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    
{% endblock %}

{% block header_button8 %}active{% endblock %}
{% block header_button1 %}active{% endblock %}


{% block content %}

    <span class="title-text">Удалить студента</span>

   <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th class="th-sm">Email
        </th>
        <th class="th-sm">ФИО
        </th>
        <th class="th-sm">Группа
        </th>
        <th class="th-sm">Курс
        </th>
        <th class="th-sm">Удалить
        </th>
        </tr>
    </thead>
    <tbody>
        {% for item in students %}
        <tr>
        <td>{{item.email}}</td>
        <td>{{item.fullname}}</td>
        <td>{{item.group}}</td>
        <td>{{item.course}}</td>
        <td class="p-0">
            <form action="{% url 'main:delete_student'%}" method="POST" >{% csrf_token %}
                <input type="hidden" name="id" value="{{item.id}}"/>
                <button type="submit" class="delete-security-button">Удалить</button>
            </form>
        </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
        <th>Email
        </th>
        <th>ФИО
        </th>
        <th>Группа
        </th>
        <th>Курс
        </th>
        <th>Удалить
        </th>
        </tr>
    </tfoot>
    </table>
   
    
{% endblock %}

main/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Вход</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="icon" type="image/png" href="{%static ''%} images/icons/favicon.ico"/>

	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animsition/css/animsition.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/daterangepicker/daterangepicker.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
    <link rel="icon" href="images/logo-cuted.png">
</head>
<body >
	
	<div class="limiter login-body" style="background:url({%static 'images/background.png'%});">
		<div class="container-login100">
			<div class="wrap-login100 ">
				<form class="login100-form validate-form flex-sb flex-w" method="post" action="{% url 'main:login'%}">{% csrf_token %}
                    <img src="{%static 'images/logo.png'%}" alt="" style="width: 150px;margin-left:auto; margin-right:auto;height:100px">
					<span class="login100-form-title p-b-51">
						Вход
					</span>

					{% if login_error%}
						<div class="error">
							{{login_error}}
						</div>
					{%endif%}

					<div class="flex-sb-m w-full p-t-3 p-b-24">
						<div>
							<a href="{%url 'main:remind_password'%}" class="txt1">
								Забыли пароль? Напомнить
							</a>
                        </div>
					</div>
					
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели данные">
						<input class="input100" type="text" name="username" placeholder="Логин или Email">
						<span class="focus-input100"></span>
					</div>
					
					
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Вы не ввели Пароль">
						<input class="input100" type="password" name="pass" placeholder="Пароль">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Войти
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{%static 'vendor/animsition/js/animsition.min.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
	<script src="{%static 'vendor/select2/select2.min.js'%}"></script>
	<script src="{%static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{%static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
	<script src="{%static 'vendor/countdowntime/countdowntime.js'%}"></script>
	<script src="{%static 'js/main.js'%}"></script>

</body>
</html>

main/templates/message.html
<link rel="stylesheet" type="text/css" href="../static/css/main.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<body class="center-div">
    <h1 class="login100-form-title p-b-51">{{text}}</h1> <br/>
    <div class="row">
        <div class="col-12">
            <a class="important-text" style="margin:30px auto;text-align:left;" href="{% url 'main:index' %}">На главную</a>
        </div>
    </div>
</body>

main/templates/stream.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <title>ShagFace</title>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/search.css'%}">
    <link rel="stylesheet" href="{%static 'css/pagination.css'%}">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
{% endblock %}

{% block header_butto10 %}active{% endblock %}
{% block header_button3 %}active{% endblock %}


{% block content %}

    <div class="camera-panel" id="camera-panel">
        <form action='{%url "main:start_stop_stream"%}' method="POST">{% csrf_token %}
            <img class="start-video" id="start" src="{% static "images/icons/camera-icons/play.png"%}" title="Start Stream"/>
            <img class="start-video" id="stop" src="{% static "images/icons/camera-icons/stop.png"%}" title="Stop Stream"/>
        </form>
    </div>
   
    <img style="-webkit-user-select: none;" class="cam-stream" id="stream" >

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        const img = document.getElementById("stream");
        

        $("#start").on("click", function(){
            $.ajax({
                url: '{% url "main:start_stop_stream"%}',
                data: {
                'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
                'is_stop': "false"
                },
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    img.src = "{% url "main:stream"%}";
                }
            });
        })

        $("#stop").on("click", function(){
            $.ajax({
                url: '{% url "main:start_stop_stream"%}',
                data: {
                    'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
                    'is_stop': "true"
                },
                type: "POST",
                dataType: 'json',
                success: function (data) {
                   img.src = "{% static "images/white.png"%}";
                }
            });
        })
    </script>
{%endblock%}